server:
  port: 8080
spring:
  application:
    name: customer
  datasource:
    password: root
    url: jdbc:postgresql://localhost:5432/customer
    username: dinu
    maximumPoolSize: 100
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  rabbitmq:
    addresses: localhost:5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true



