server:
  port: 8081
spring:
  application:
    name: fraud
  datasource:
    password: root
    url: jdbc:postgresql://postgres:5432/fraud
    username: dinu
    maximumPoolSize: 100
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true


